function createPulseFixscript(params)

% Writes shell scripts to fix a bug with Siemens pulse data
%
%   Usage:
%   createPulseFixscript(params)
%
%   Written by Andrew S Bock Oct 2016

%% Set initial parameters
fname = fullfile(params.outDir,[params.jobName '_fixPulse.sh']);
fid = fopen(fname,'w');
fprintf(fid,'#!/bin/bash\n');
fprintf(fid,['SESS=' params.sessionDir '\n']);
fprintf(fid,['SUBJ=' params.subjectName '\n\n']);
matlab_string = '"';
%% Add functional scripts
for rr = 1:params.numRuns
    func = 'rf';
    matlab_string = [matlab_string ...
        'create_regressors(''$SESS'',' num2str(rr) ',''' func ''',''detrend'',' ...
        num2str(params.lowHz) ',' num2str(params.highHz) ',' num2str(params.physio) ',' ...
        num2str(params.motion) ',' num2str(params.anat) ');' ...
        'remove_noise(''$SESS'',' num2str(rr) ',''' func ''',' ...
        num2str(params.task) ',' num2str(params.anat) ',' num2str(params.motion) ',' ...
        num2str(params.physio) ');'];
    if params.localWM
        matlab_string = [matlab_string ...
            'remove_localWM(''$SESS'',' num2str(rr) ',''d' func ''');' ...
            'temporal_filter(''$SESS'',' num2str(rr) ',''wd' func ''',''' params.filtType ''',' ...
            num2str(params.lowHz) ',' num2str(params.highHz) ');' ...
            'smooth_vol_surf(''$SESS'',' num2str(rr) ',5,''wd' func '.tf'');'];
    else
        matlab_string = [matlab_string ...
            'temporal_filter(''$SESS'',' num2str(rr) ',''d' func ''',''' params.filtType ''',' ...
            num2str(params.lowHz) ',' num2str(params.highHz) ');' ...
            'smooth_vol_surf(''$SESS'',' num2str(rr) ',5,''d' func '.tf'');'];
    end
end
fprintf(fid,['matlab -nodisplay -nosplash -r ' matlab_string '"']);
fclose(fid);