% Master script for processing data in the Human Connectome Low Vision
% (HCLV) project
%
%   Written by Andrew S Bock Sep 2016

%% Defaults
logDir                  = '/data/jag/TOME/LOGS';
params.despike          = 1;
params.slicetiming      = 0;
params.topup            = 1;
params.refvol           = 1;
params.regFirst         = 1;
params.filtType         = 'high';
params.lowHz            = 0.01;
params.highHz           = 0.10;
params.physio           = 1;
params.motion           = 1;
params.task             = 0;
params.localWM          = 1;
params.anat             = 1;
params.amem             = 20;
params.fmem             = 50;
% for pRF scripts
hemis                   = {'lh' 'rh'};
pRFfunc                 = 'wdrf.tf.surf';
params.sigList          = 0.5:0.1:10;
% for eye tracking
[~, tmpName]            = system('whoami');
userName                = strtrim(tmpName);
dbDir                   = ['/Users/' userName '/Dropbox-Aguirre-Brainard-Lab'];
%% Example subject - session 1 - PREPROCESSING
params.sessionDir       = '/data/jag/TOME/TOME_3001/081916a';
params.subjectName      = 'TOME_3001';
params.outDir           = fullfile(params.sessionDir,'preprocessing_scripts');
params.logDir           = logDir;
params.jobName          = params.subjectName;
params.numRuns          = 4;
params.reconall         = 1;
create_preprocessing_scripts(params);
%% Example subject - session 1 - EYE TRACKING


%% Example subject - session 1 - RETINOTOPY


%% Example subject - session 2 - preprocessing

%%% copy MPRAGE directory from session 1 %%%

params.sessionDir       = '/data/jag/TOME/TOME_3001/081916b';
params.subjectName      = 'TOME_3001';
params.outDir           = fullfile(params.sessionDir,'preprocessing_scripts');
params.logDir           = logDir;
params.jobName          = params.subjectName;
params.numRuns          = 10;
params.reconall         = 0;
create_preprocessing_scripts(params);
%% Example subject - session 2 - EYE TRACKING


%% Example subject - session 2 - RETINOTOPY



%% Subject information
% Session 1
sessionDirs                = {...
    '/data/jag/TOME/TOME_3001/081916a' ...
    '/data/jag/TOME/TOME_3002/082616a' ...
    '/data/jag/TOME/TOME_3002/082616b' ...
    '/data/jag/TOME/TOME_3003/090216' ...
    '/data/jag/TOME/TOME_3003/091616' ...
    '/data/jag/TOME/TOME_3005/092316' ...
    '/data/jag/TOME/TOME_3005/100316' ...
    '/data/jag/TOME/TOME_3007/101116' ...
    '/data/jag/TOME/TOME_3007/101716' ...
    };
% sessionDirs                = {...
%     '/data/jag/TOME/TOME_3001/081916a' ...
%     '/data/jag/TOME/TOME_3001/081916b' ...
%     '/data/jag/TOME/TOME_3002/082616a' ...
%     '/data/jag/TOME/TOME_3002/082616b' ...
%     '/data/jag/TOME/TOME_3003/090216' ...
%     '/data/jag/TOME/TOME_3003/091616' ...
%     '/data/jag/TOME/TOME_3004/091916' ...
%     '/data/jag/TOME/TOME_3004/092016' ...
%     '/data/jag/TOME/TOME_3004/101416a' ...
%     '/data/jag/TOME/TOME_3004/101416b' ...
%     '/data/jag/TOME/TOME_3005/092316' ...
%     '/data/jag/TOME/TOME_3005/100316' ...
%     '/data/jag/TOME/TOME_3007/101116' ...
%     '/data/jag/TOME/TOME_3007/101716' ...
%     '/data/jag/TOME/TOME_3009/100716' ...
%     '/data/jag/TOME/TOME_3009/102516' ...
%     '/data/jag/TOME/TOME_3011/111116' ...
%     };
sessionNames               = {...
    'TOME_3001' ...
    'TOME_3002' ...
    'TOME_3002' ...
    'TOME_3003' ...
    'TOME_3003' ...
    'TOME_3005' ...
    'TOME_3005' ...
    'TOME_3007' ...
    'TOME_3007' ...
    };
% sessionNames               = {...
%     'TOME_3001' ...
%     'TOME_3001' ...
%     'TOME_3002' ...
%     'TOME_3002' ...
%     'TOME_3003' ...
%     'TOME_3003' ...
%     'TOME_3004' ...
%     'TOME_3004' ...
%     'TOME_3004' ...
%     'TOME_3004' ...
%     'TOME_3005' ...
%     'TOME_3005' ...
%     'TOME_3007' ...
%     'TOME_3007' ...
%     'TOME_3009' ...
%     'TOME_3009' ...
%     'TOME_3011' ...
%     };

numRuns = [...
    4 ...
    4 ...
    10 ...
    4 ...
    10 ...
    4 ...
    10 ...
    4 ...
    10 ...
    ];
% numRuns = [...
%     4 ...
%     10 ...
%     4 ...
%     10 ...
%     4 ...
%     10 ...
%     4 ...
%     10 ...
%     10 ...
%     2 ...
%     4 ...
%     10 ...
%     4 ...
%     10 ...
%     4 ...
%     10 ...
%     4 ...
%     ];
reconall = [...
    0 ...
    0 ...
    0 ...
    0 ...
    0 ...
    0 ...
    0 ...
    0 ...
    0 ...
    ];

% reconall = [...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     0 ...
%     1 ...
%     0 ...
%     1 ...
%     ];
%% Create preprocessing scripts
for i = 1:length(sessionDirs)
    params.sessionDir       = sessionDirs{i};
    params.subjectName      = sessionNames{i};
    params.outDir           = fullfile(params.sessionDir,'preprocessing_scripts');
    params.logDir           = logDir;
    params.jobName          = params.subjectName;
    params.numRuns          = numRuns(i);
    params.reconall         = reconall(i);
    create_preprocessing_scripts(params);
end
%% MPRAGE directory %%%
% Before submitting the session 2 preprocessing scripts, be sure to copy
% copy over the MPRAGE directory from session 1
%% Submit scripts
% navigate to the <sessionDir>/preprocessing_scripts directory for each
% session and submit the appropriate shell script (e.g. sh
% submit_TOME_3001_all.sh)

%% Eye tracking
subject                 = 'TOME_3009';
session                 = '102516';
dataDir                 = fullfile(dbDir,'tome_data/session2_spatialStimuli');
thisDir                 = fullfile(dataDir,subject,session,'EyeTracking');
params.scaleCalVideo    = fullfile(thisDir,'ScaleCalibration_5Mm_102516_170031.avi');
params.scaleCalOutVideo = fullfile('~','ScaleCalibration_5Mm_102516_170031.avi');
params.scaleCalOutMat   = fullfile('~','ScaleCalibration_5Mm_102516_170031.mat');
params.calTargetFile    = fullfile(thisDir,'GazeCal01_LTdat.mat');
params.gazeCalVideo     = fullfile(thisDir,'GazeCal01.mov');
params.gazeCalOutVideo  = fullfile('~','GazeCal01.avi');
params.gazeCalOutMat    = fullfile('~','GazeCal01.mat');
params.gazeCalVideo     = fullfile(thisDir,'GazeCal01.mov');
params.fMRIVideo        = fullfile(thisDir,'tfMRI_MOVIE_AP_run01_raw.mov');
params.fMRIOutVideo     = fullfile('~','tfMRI_MOVIE_AP_run01_raw.avi');
params.fMRIOutMat       = fullfile('~','tfMRI_MOVIE_AP_run01_raw.mat');
[pupilSize,gaze]        = calcPupilFMRI(params);

%% Project retinotopic templates
for i = 1:length(sessionDirs)
    project_template(sessionDirs{i},sessionNames{i});
end

%% make pRF scripts
params.logDir                   = logDir;
for i = 2:2:10%length(sessionDirs)
    params.scriptDir            = fullfile(sessionDirs{i},'pRFscripts');
    d = listdir(fullfile(sessionDirs{i},'*tfMRI_RETINO*'),'dirs');
    s = listdir(fullfile(sessionDirs{i},'Stimuli','tfMRI_RETINO*'),'files');
    for j = 1:length(d)
        for k = 1:length(hemis)
            params.jobName      = sprintf([hemis{k} '.pRF.%02d.sh'],j);
            tmpInd              = strfind(s,sprintf('%02d',j));
            stimInd             = find(~cellfun(@isempty,tmpInd));
            params.stimFile     = fullfile(sessionDirs{i},'Stimuli',s{stimInd});
            params.inVol        = fullfile(sessionDirs{i},d{j},[pRFfunc '.' hemis{k} '.nii.gz']);
            params.outDir       = fullfile(sessionDirs{i},d{j});
            params.baseName     = hemis{k};
            makePRFscripts(params);
        end
    end
    params.submitName           = 'submit.pRF.sh';
    makePRFsubmit(params);
end
%% submit pRF scripts
%
%   submit the scripts above
%% Average pRF maps across runs
for i = 2:2:length(sessionDirs)
    for j = 1:length(hemis);
        params.sessionDir       = sessionDirs{i};
        params.baseName         = hemis{j};
        avgPRFmaps(params);
    end
end