% Master script for processing data in the Human Connectome Low Vision
% (HCLV) project
%
%   Written by Andrew S Bock Sep 2016

%% Defaults
logDir                  = '/data/jag/TOME/LOGS';
params.despike          = 1;
params.slicetiming      = 0;
params.topup            = 1;
params.refvol           = 1;
params.regFirst         = 1;
params.filtType         = 'high';
params.lowHz            = 0.01;
params.highHz           = 0.10;
params.physio           = 1;
params.motion           = 1;
params.task             = 0;
params.localWM          = 1;
params.anat             = 1;
params.amem             = 20;
params.fmem             = 50;
% for pRF scripts
hemis                   = {'lh' 'rh'};
pRFfunc                 = 'wdrf.tf.surf';
params.sigList          = 0.5:0.1:10;
%% Subject information
% Session 1
sessionDirs                = {...
    '/data/jag/TOME/TOME_3001/081916a' ...
    '/data/jag/TOME/TOME_3001/081916b' ...
    '/data/jag/TOME/TOME_3002/082616a' ...
    '/data/jag/TOME/TOME_3002/082616b' ...
    '/data/jag/TOME/TOME_3003/090216' ...
    '/data/jag/TOME/TOME_3003/091616' ...
    '/data/jag/TOME/TOME_3004/091916' ...
    '/data/jag/TOME/TOME_3004/092016' ...
    '/data/jag/TOME/TOME_3004/101416a' ...
    '/data/jag/TOME/TOME_3004/101416b' ...
    '/data/jag/TOME/TOME_3005/092316' ...
    '/data/jag/TOME/TOME_3005/100316' ...
    '/data/jag/TOME/TOME_3007/101116' ...
    '/data/jag/TOME/TOME_3007/101716' ...
    '/data/jag/TOME/TOME_3009/100716' ...
    '/data/jag/TOME/TOME_3009/102516' ...
    };
sessionNames               = {...
    'TOME_3001' ...
    'TOME_3001' ...
    'TOME_3002' ...
    'TOME_3002' ...
    'TOME_3003' ...
    'TOME_3003' ...
    'TOME_3004' ...
    'TOME_3004' ...
    'TOME_3004' ...
    'TOME_3004' ...
    'TOME_3005' ...
    'TOME_3005' ...
    'TOME_3007' ...
    'TOME_3007' ...
    'TOME_3009' ...
    'TOME_3009' ...
    };
numRuns = [...
    4 ...
    10 ...
    4 ...
    10 ...
    4 ...
    10 ...
    4 ...
    10 ...
    10 ...
    2 ...
    4 ...
    10 ...
    4 ...
    10 ...
    4 ...
    10 ...
    ];
reconall = [...
    1 ...
    0 ...
    1 ...
    0 ...
    1 ...
    0 ...
    1 ...
    0 ...
    0 ...
    0 ...
    1 ...
    0 ...
    1 ...
    0 ...
    1 ...
    0 ...
    ];
%% Create preprocessing scripts
for i = 1:length(sessionDirs)
    params.sessionDir       = sessionDirs{i};
    params.subjectName      = sessionNames{i};
    params.outDir           = fullfile(params.sessionDir,'preprocessing_scripts');
    params.logDir           = logDir;
    params.jobName          = params.subjectName;
    params.numRuns          = numRuns(i);
    params.reconall         = reconall(i);
    create_preprocessing_scripts(params);
end
%% MPRAGE directory %%%
% Before submitting the session 2 preprocessing scripts, be sure to copy
% copy over the MPRAGE directory from session 1
%% Submit scripts
% navigate to the <sessionDir>/preprocessing_scripts directory for each
% session and submit the appropriate shell script (e.g. sh
% submit_TOME_3001_all.sh)
%% Project retinotopic templates
for i = 1:length(sessionDirs)
    project_template(sessionDirs{i},sessionNames{i});
end

%% make pRF scripts
params.logDir                   = logDir;
for i = 2:2:length(sessionDirs)
    params.scriptDir            = fullfile(sessionDirs{i},'pRFscripts');
    d = listdir(fullfile(sessionDirs{i},'*tfMRI_RETINO*'),'dirs');
    s = listdir(fullfile(sessionDirs{i},'Stimuli','tfMRI_RETINO*'),'files');
    for j = 1:length(d)
        for k = 1:length(hemis)
            params.jobName      = sprintf([hemis{k} '.pRF.%02d.sh'],j);
            tmpInd              = strfind(s,sprintf('%02d',j));
            stimInd             = find(~cellfun(@isempty,tmpInd));
            params.stimFile     = fullfile(sessionDirs{i},'Stimuli',s{stimInd});
            params.inVol        = fullfile(sessionDirs{i},d{j},[pRFfunc '.' hemis{k} '.nii.gz']);
            params.outDir       = fullfile(sessionDirs{i},d{j});
            params.baseName     = hemis{k};
            makePRFscripts(params);
        end
    end
    params.submitName           = 'submit.pRF.sh';
    makePRFsubmit(params);
end
%% Average pRF maps across runs
for i = 2%:2:length(sessionDirs)
    for j = 1:length(hemis);
        params.sessionDir       = sessionDirs{i};
        params.baseName         = hemis{j};
        avgPRFmaps(params);
    end
end